# =============================================================================
# DOCKER COMPOSE FOR SSL CERTIFICATE SETUP
# =============================================================================
# Temporary setup to obtain SSL certificates with Certbot
# Use this before deploying the production stack

services:
  # Temporary Nginx for SSL certificate validation
  nginx-certbot:
    image: nginx:1.25-alpine
    container_name: nginx_certbot_temp
    
    ports:
      - "80:80"
    
    volumes:
      - ./nginx/certbot.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    
    restart: unless-stopped
    
    command: >
      sh -c "nginx -g 'daemon off;'"

  # Certbot service for obtaining certificates
  certbot:
    image: certbot/certbot:latest
    container_name: certbot_temp
    
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    
    profiles:
      - certbot
    
    # Run certbot to obtain certificates
    # Usage: docker-compose -f docker-compose.ssl-setup.yml --profile certbot run --rm certbot certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d your-domain.com